### PR TITLE
Add support for table type responses

### LINKED ISSUE #24: Unable to handle Table responses
**Actual Behaviour**

The SUSI AI Twitch bot is not able to handle table type responses.
screen shot 2018-05-26 at 9 12 10 am

**Expected Behaviour**

These responses should be handled perfectly.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by DNS-404**
Fixes #24 

Challenges and changes:
- Character limit for one message is around 450 so only 4 results will be shown.
- Can not send multiple texts on Twitch very fast. They get blocked. Would have to use some time delay which won't be good. So I'm just displaying 4 results in one text.
- New line can't be added using `\n` on Twitch so I'm using ` | ` to separate different rows.

Screenshots for the change: 

screen shot 2018-05-27 at 4 02 43 pm

### CODE REVIEW

**Comment by AliAyub007** [comment]
@DNS-404 There is no travis file in repository that's why travis is failing. Kindly add travis.yml

**Comment by DNS-404** [comment]
@AliAyub007 What should I add to `travis.yml` file? 😅

**Comment by DNS-404** [comment]
@AliAyub007 I added the file. It's still failing. 😟Please check.

**Comment by anshumanv** [comment]
You need to commit the travis file first, then it will be used in further PRs.

**Comment by AliAyub007** [comment]
@DNS-404 Kindly mention your fellows to review this PR.

**Comment by DNS-404** [comment]
@hkedia321 @Akshat-Jain @anshumanv @PrP-11 @akshatnitd Please review.

**Pull request merged**
